### ISSUE TITLE
Alderley Day/Night Dataset

### ISSUE THREAD

**Issue by jiangcheng0128** [qcr/qcr.github.io#33]
How can I obtain this dataset? https://wiki.qut.edu.au/pages/viewpage.action?pageId=181178395 cannot been opened.

**Comment by Tobias-Fischer** [comment]
@Timothy-Morris - any idea what we can do here? I think there are lots of datasets which used to be on the public-facing QCR wiki, but now that the wiki is login only people outside QUT can't access the pages anymore.

**Comment by jiangcheng0128** [comment]
> @Timothy-Morris - any idea what we can do here? I think there are lots of datasets which used to be on the public-facing QCR wiki, but now that the wiki is login only people outside QUT can't access the pages anymore.

Is there a way that I can access the database outside the QUT or if it is possible for you to transfer it to me through Google Driver or some other software prefer? Thank you!

**Comment by Tobias-Fischer** [comment]
Here is some information and download links:

<p style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0px; padding: 0px;">This is a vehicle dataset for vision-based place recognition with manually ground truthed frame correspondences. The dataset was captured in two different conditions for the same route: one on a sunny day and one during a rainy night. Both datasets were taken in the suburb of Alderley, Queensland.</p><div class="table-wrap" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 10px 0px 0px; padding: 0px; overflow-x: auto;">
</div>


If you use or refer to this dataset, please cite the following paper:
M. Milford, G. Wyeth, "SeqSLAM: Visual route-based navigation for sunny summer days and stormy winter nights", in IEEE International Conference on Robotics and Automation, St Paul, United States, 2012.
BibTeX, Endnote, RefMan and CSV citation options available by [clicking here](http://scholar.google.com/citations?hl=en&user=TDSmCKgAAAAJ&citation_for_view=TDSmCKgAAAAJ:j3f4tGmQtD8C&view_op=view_citation).

Here is a .zip file containing all of the files described below:
[DOWNLOADABLE ZIP FILE](https://mega.nz/#!xM0WmKYR!YhvoxMAqK-qlSg7Xxgr--GN5WDqmXDV6B6YIQ1o72MI) | [ALTERNATIVE DOWNLOAD LINK](https://www.dropbox.com/s/ejmnz9vfp4n7o7s/alderley.zip?dl=0)
Attached below are the original .avi movie files as well as the individual frames, extracted from the video and compressed into zip files. A .csv file holds the frame correspondences, which is replicated in the MATLAB mat file (requires MATLAB to use). The frame correspondences can be visually validated using the MATLAB script PLAYBACK.m. This will play back the videos, aligned using the frame correspondences in fm.mat.
FRAMESA corresponds to the night time traverse and FRAMESB to the day time traverse.


<p style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 10px 0px 0px; padding: 0px; caret-color: rgb(23, 43, 77); color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px;">FRAMESA corresponds to the night time traverse and FRAMESB to the day time traverse.</p><div class="table-wrap" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 10px 0px 0px; padding: 0px; overflow-x: auto; caret-color: rgb(23, 43, 77); color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px;">

Original Video Files (.avi format) | Extracted Frames | Frame Correspondences | MATLAB Resources
-- | -- | -- | --
night1_orig.aviday1_orig.avi | FRAMESA.zip - this contains the frames from night1_orig.aviFRAMESB.zip - this contains the frames from day1_orig.avi | framematches.csv - column 1 is FRAMESA and column 2 is FRAMESB | fm.mat - frame correspondencesPLAYBACK.m - for validation of ground truth

</div>


Other Papers Using this Dataset
M Milford, W Scheirer, E Vig, A Glover, O Baumann, J Mattingley, D Cox, "[Condition-Invariant, Top-Down Visual Place Recognition](http://scholar.google.com/citations?view_op=view_citation&hl=en&user=TDSmCKgAAAAJ&sortby=pubdate&citation_for_view=TDSmCKgAAAAJ:M05iB0D1s5AC)",  in IEEE International Conference on Robotics and Automation, Hong Kong, China, 2014.

**Comment by jiangcheng0128** [comment]
Thank you very much for your reply ！
